server:
  port: 8004
mybatis:
  mapper-locations: classpath:mapper/**/*
  type-aliases-package: com.gx.community.pojo
  config-location: classpath:SqlMapConfig.xml
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://192.168.22.46:3306/db_community?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: GZXD17302
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      initial-size: 5
      min-idle: 5
      max-active: 50
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      filters: stat,wall,log4j2
      test-while-idle: true
  redis:
    host: 192.168.22.46
    port: 6379
    password: GZXD17302
  application:
    name: microservicecloud-student

wx:
  miniapp:
    config:
      appid: wx73c13a1e77833a29
      secret: aca58e05adddb9a57055e844130f2c63
      msgDataFormat: JSON

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: student8004
    prefer-ip-address: true