server:
  port: 8080

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: consumer8080
    prefer-ip-address: true
spring:
  application:
    name: microservicecloud-consumer