server:
  port: 80

spring:
  application:
    name: microservice-gateway-zuul

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:

zuul:
  routes:
    consumer:
      path: /consumer/**
      service-id: MICROSERVICECLOUD-CONSUMER